name 'postgresql-cluster'
maintainer 'Irving Popovetsky'
maintainer_email 'irving@chef.io'
license 'all_rights'
description 'Installs/Configures postgresql-cluster'
long_description 'Installs/Configures postgresql-cluster'
version '0.3.0'
source_url       'https://github.com/irvingpop/postgresql-cluster'
issues_url       'https://github.com/irvingpop/postgresql-cluster/issues'

depends 'postgresql'
depends 'pgpool'
depends 'hostsfile'
depends 'chef-provisioning-vagrant-helper'
depends 'chef-provisioning-aws-helper'
#depends 'ssh_authorized_keys' # TODO: use the resources provided by this cookbook

supports 'ubuntu', '>= 12.04'
supports 'centos', '>= 7.1'
supports 'redhat', '>= 7.1'
