name 'postgresql-cluster'
maintainer 'Irving Popovetsky'
maintainer_email 'irving@chef.io'
license 'all_rights'
description 'Installs/Configures postgresql-cluster'
long_description 'Installs/Configures postgresql-cluster'
version '0.1.0'
source_url       'https://github.com/irvingpop/postgresql-cluster'
issues_url       'https://github.com/irvingpop/postgresql-cluster/issues'

depends 'postgresql'
depends 'pgpool'
depends 'hostsfile'
depends 'chef-provisioning-vagrant-helper'
depends 'chef-provisioning-aws-helper'
